### PR TITLE
Convert `protoc` plugin to Go

### PR DESCRIPTION
**Pull request by pojntfx**
This PR converts the current TypeScript-based generator to Go for embeddability and significant speed improvments. It retains the previous integration tests and adds new Go snapshot tests for the `protoc` plugin.

### CODE REVIEW

**Review by ShivanshVij — APPROVED** [review]
LGTM, we should probably update the readme to make it clear that you can install it using "go get" the same way we do in the polyglot-go repo

**Comment by pojntfx** [comment]
That's a good idea, should I keep the `curl` install methods as well? Keeping in mind that this is for JS devs I don't think we should require the Go toolchain to be available

**Comment by ShivanshVij** [comment]
> That's a good idea, should I keep the `curl` install methods as well? Keeping in mind that this is for JS devs I don't think we should require the Go toolchain to be available

Yep keep them all. The go one is really just to keep things consistent.

**Comment by pojntfx** [comment]
Great, I added a `go install` section just now!

**Pull request merged**
